### ISSUE TITLE
reboot random MMROM ICS 20121105

### ISSUE THREAD

**Issue by bulldozercore** [mmontuori/atrix-mrom#23]
[96] DiskBasedCache.clear: Cache cleared.

[ 11-06 13:58:12.420  6329:0x18cd D/Volley   ]
[100] DiskBasedCache.clear: Cache cleared.

[ 11-06 13:58:12.440  6329:0x18b9 D/Finsky   ]
[1] 2.run: Loaded library for account: [iKSO-zZAyuc_Aw8CPvCv72Jb3pw]

[ 11-06 13:58:12.440  6329:0x18b9 D/Finsky   ]
[1] 2.run: Finished loading 1 libraries.

[ 11-06 13:58:12.470  5697:0x1711 I/ActivityManager ]
Start proc com.keramidas.TitaniumBackup for broadcast com.keramidas.TitaniumBack
up/.schedules.BootReceiver: pid=6375 uid=10070 gids={1015, 3003}

[ 11-06 13:58:12.530  6375:0x18e7 I/com.keramidas.TitaniumBackup.MainApplication
 ]
onCreate()

[ 11-06 13:58:12.530  6375:0x18e7 D/dalvikvm ]
Trying to load lib /data/data/com.keramidas.TitaniumBackup/lib/libtitanium.so 0x
40e59408

[ 11-06 13:58:12.530  6375:0x18e7 D/dalvikvm ]
Added shared lib /data/data/com.keramidas.TitaniumBackup/lib/libtitanium.so 0x40
e59408

[ 11-06 13:58:12.580  6375:0x18e7 I/com.keramidas.TitaniumBackup.MainApplication
 ]
Detected CPU architecture: ARM

[ 11-06 13:58:12.590  6375:0x18e7 W/Settings ]
Setting android_id has moved from android.provider.Settings.System to android.pr
ovider.Settings.Secure, returning read-only value.

[ 11-06 13:58:12.590  6375:0x18e7 D/hq       ]
Debug features are disabled.

[ 11-06 13:58:12.590  6375:0x18e7 I/hh       ]
restoreMySettings_ifNeeded()

[ 11-06 13:58:12.590  6375:0x18e7 I/hh       ]
Internal settings found => No need to restore.

[ 11-06 13:58:12.630  6375:0x18e7 W/Resources ]
Converting to string: TypedValue{t=0x10/d=0x0 a=-1}

[ 11-06 13:58:12.630  6375:0x18e7 W/Resources ]
Converting to string: TypedValue{t=0x10/d=0x0 a=-1}

[ 11-06 13:58:12.630  6375:0x18e7 W/Resources ]
Converting to string: TypedValue{t=0x10/d=0x0 a=-1}

[ 11-06 13:58:12.630  6375:0x18e7 W/Resources ]
Converting to string: TypedValue{t=0x10/d=0xf a=-1}

[ 11-06 13:58:12.640  6375:0x18e7 W/Resources ]
Converting to string: TypedValue{t=0x10/d=0x80 a=-1}

[ 11-06 13:58:12.640  6375:0x18e7 W/Resources ]
Converting to string: TypedValue{t=0x10/d=0x80 a=-1}

[ 11-06 13:58:12.640  6375:0x18e7 W/Resources ]
Converting to string: TypedValue{t=0x10/d=0x3 a=-1}

[ 11-06 13:58:12.640  6375:0x18e7 W/Resources ]
Converting to string: TypedValue{t=0x10/d=0x3 a=-1}

[ 11-06 13:58:12.640  6375:0x18e7 W/Resources ]
Converting to string: TypedValue{t=0x10/d=0x20 a=-1}

[ 11-06 13:58:12.640  6375:0x18e7 W/Resources ]
Converting to string: TypedValue{t=0x10/d=0x20 a=-1}

[ 11-06 13:58:12.640  6375:0x18e7 W/Resources ]
Converting to string: TypedValue{t=0x10/d=0x1 a=-1}

[ 11-06 13:58:12.650  6375:0x18e7 W/Resources ]
Converting to string: TypedValue{t=0x10/d=0x3 a=-1}

[ 11-06 13:58:12.650  6375:0x18e7 W/Resources ]
Converting to string: TypedValue{t=0x10/d=0x3 a=-1}

[ 11-06 13:58:12.660  6375:0x18e7 I/com.keramidas.TitaniumBackup.schedules.BootR
eceiver ]
Boot has completed => Scheduling next wake-up ...

[ 11-06 13:58:12.660  6375:0x18e7 I/com.keramidas.TitaniumBackup.schedules.Sched
ulerService ]
scheduleNextWakeup(): Invoked with idToExcludeForToday=null

[ 11-06 13:58:12.710  6375:0x18e7 I/com.keramidas.TitaniumBackup.schedules.Sched
ulerService ]
scheduleNextWakeup(): No next wakeup scheduled.

[ 11-06 13:58:12.730  6391:0x18f7 D/dalvikvm ]
Late-enabling CheckJNI

[ 11-06 13:58:12.730  5697:0x16fa I/ActivityManager ]
Start proc com.dimonvideo.luckypatcher for broadcast com.dimonvideo.luckypatcher
/.OnBootLuckyPatcher: pid=6391 uid=10069 gids={3003, 1015, 1007}

[ 11-06 13:58:12.730  5697:0x16fa I/ActivityManager ]
No longer want com.android.deskclock (pid 6147): hidden #16

[ 11-06 13:58:12.750  6391:0x18f7 I/dalvikvm ]
Turning on JNI app bug workarounds for target SDK version 4...

[ 11-06 13:58:12.770  6391:0x18f7 I/System.out ]
LuckyPatcher: Application Start!

[ 11-06 13:58:12.770  6391:0x18f7 I/System.out ]
luuuuu Intent { act=android.intent.action.BOOT_COMPLETED flg=0x10 cmp=com.dimonv
ideo.luckypatcher/.OnBootLuckyPatcher }

[ 11-06 13:58:12.780  6391:0x18f7 I/System.out ]
LuckyPatcher (count patches to boot): 3

[ 11-06 13:58:12.780  6391:0x18f7 I/System.out ]
luuuuu 13

[ 11-06 13:58:12.780  6391:0x18f7 I/System.out ]
luuuuu 13

[ 11-06 13:58:12.780  6391:0x18f7 I/System.out ]
luuuuu 13

[ 11-06 13:58:12.810  6391:0x18f7 I/System   ]
Failed to destroy process 6405

[ 11-06 13:58:12.810  6391:0x18f7 I/System   ]
libcore.io.ErrnoException: kill failed: ESRCH (No such process)
        at libcore.io.Posix.kill(Native Method)
        at libcore.io.ForwardingOs.kill(ForwardingOs.java:77)
        at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:257)

```
    at com.dimonvideo.luckypatcher.OnBootLuckyPatcher.onReceive(OnBootLuckyP
```

atcher.java:342)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2242)
        at android.app.ActivityThread.access$1500(ActivityThread.java:132)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4575)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit
.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
        at dalvik.system.NativeStart.main(Native Method)

[ 11-06 13:58:12.850  6391:0x18f7 I/System   ]
Failed to destroy process 6410

[ 11-06 13:58:12.850  6391:0x18f7 I/System   ]
libcore.io.ErrnoException: kill failed: ESRCH (No such process)
        at libcore.io.Posix.kill(Native Method)
        at libcore.io.ForwardingOs.kill(ForwardingOs.java:77)
        at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:257)

```
    at com.dimonvideo.luckypatcher.OnBootLuckyPatcher.onReceive(OnBootLuckyP
```

atcher.java:342)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2242)
        at android.app.ActivityThread.access$1500(ActivityThread.java:132)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4575)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit
.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
        at dalvik.system.NativeStart.main(Native Method)

[ 11-06 13:58:12.860  5697:0x1641 I/ActivityManager ]
No longer want com.android.exchange (pid 6165): hidden #16

[ 11-06 13:58:12.900  5697:0x164c I/ActivityManager ]
Start proc com.android.calendar for broadcast com.android.calendar/.widget.Calen
darAppWidgetProvider: pid=6414 uid=10009 gids={3003}

[ 11-06 13:58:12.970  6409:0x1909 D/AndroidRuntime ]

> > > > > > AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<

[ 11-06 13:58:12.970  6409:0x1909 D/AndroidRuntime ]
CheckJNI is OFF

[ 11-06 13:58:12.970  6413:0x190d D/AndroidRuntime ]

> > > > > > AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<

[ 11-06 13:58:12.970  6413:0x190d D/AndroidRuntime ]
CheckJNI is OFF

[ 11-06 13:58:12.970  6413:0x190d D/dalvikvm ]
DexOpt: sleeping on flock(/cache/dalvik-cache/system@framework@core.jar@classes.
dex)

[ 11-06 13:58:12.980  6409:0x1909 D/dalvikvm ]
DexOpt: sleeping on flock(/cache/dalvik-cache/system@framework@bouncycastle.jar@
classes.dex)

[ 11-06 13:58:13.020  6414:0x190e I/ActivityThread ]
Pub com.android.calendar.CalendarRecentSuggestionsProvider: com.android.calendar
.CalendarRecentSuggestionsProvider

[ 11-06 13:58:13.090  5697:0x16de I/ActivityManager ]
No longer want com.android.mms (pid 6180): hidden #16

[ 11-06 13:58:13.220  6413:0x190d D/AndroidRuntime ]
Calling main entry com.android.commands.am.Am

[ 11-06 13:58:13.220  5697:0x1712 D/CountryDetector ]
No listener is left

[ 11-06 13:58:13.230  6409:0x1909 D/AndroidRuntime ]
Calling main entry com.android.commands.am.Am

[ 11-06 13:58:13.230  6224:0x1850 E/SuperSU  ]
[SuperSU] onReceive

[ 11-06 13:58:13.240  6413:0x190d D/AndroidRuntime ]
Shutting down VM

[ 11-06 13:58:13.240  6413:0x192f I/AndroidRuntime ]
NOTE: attach of thread 'Binder Thread #3' failed

[ 11-06 13:58:13.240  6413:0x1923 D/dalvikvm ]
GC_CONCURRENT freed 100K, 88% free 491K/4096K, paused 0ms+1ms

[ 11-06 13:58:13.250  6224:0x1850 E/SuperSU  ]
[SuperSU] onReceive

[ 11-06 13:58:13.250  6409:0x1909 D/AndroidRuntime ]
Shutting down VM

[ 11-06 13:58:13.260  6409:0x1930 I/AndroidRuntime ]
NOTE: attach of thread 'Binder Thread #3' failed

[ 11-06 13:58:13.260  6409:0x1924 D/dalvikvm ]
GC_CONCURRENT freed 100K, 88% free 491K/4096K, paused 1ms+1ms

[ 11-06 13:58:14.150  5630:0x161a D/HWC_HDMI_MOT ]
wait_for_extdisp_service: try to connect to ExtDisp service IPC

[ 11-06 13:58:14.150  5630:0x161a E/HWC_HDMI_MOT ]
connectToExtDispIpc: Client Failed, No IPC Server

[ 11-06 13:58:15.240  5697:0x1651 I/ActivityManager ]
Start proc com.android.providers.calendar for broadcast com.android.providers.ca
lendar/.CalendarProviderBroadcastReceiver: pid=6449 uid=10010 gids={3003, 1015}

[ 11-06 13:58:15.270  5631:0x15ff D/dalvikvm ]
GC_EXPLICIT freed 37K, 83% free 2207K/12288K, paused 2ms+2ms

[ 11-06 13:58:15.290  5631:0x15ff D/dalvikvm ]
GC_EXPLICIT freed <1K, 83% free 2207K/12288K, paused 1ms+2ms

[ 11-06 13:58:15.300  6449:0x1931 I/ActivityThread ]
Pub com.android.calendar: com.android.providers.calendar.CalendarProvider2

[ 11-06 13:58:15.310  5631:0x15ff D/dalvikvm ]
GC_EXPLICIT freed <1K, 83% free 2207K/12288K, paused 1ms+2ms

[ 11-06 13:58:16.150  5630:0x161a D/HWC_HDMI_MOT ]
wait_for_extdisp_service: try to connect to ExtDisp service IPC

[ 11-06 13:58:16.150  5630:0x161a E/HWC_HDMI_MOT ]
connectToExtDispIpc: Client Failed, No IPC Server

[ 11-06 13:58:16.820  6449:0x1931 I/CalendarProvider2 ]
Sending notification intent: Intent { act=android.intent.action.PROVIDER_CHANGED
 dat=content://com.android.calendar }

[ 11-06 13:58:16.820  6449:0x1931 W/ContentResolver ]
Failed to get type for: content://com.android.calendar (Unknown URL content://co
m.android.calendar)

[ 11-06 13:58:16.850  5697:0x1711 I/ActivityManager ]
No longer want com.cyanogenmod.settings.device (pid 6207): hidden #16

[ 11-06 13:58:18.150  5630:0x161a D/HWC_HDMI_MOT ]
wait_for_extdisp_service: try to connect to ExtDisp service IPC

[ 11-06 13:58:18.150  5630:0x161a E/HWC_HDMI_MOT ]
connectToExtDispIpc: Client Failed, No IPC Server

**Comment by mmontuori** [comment]
are you still having reboots with the latest version?
